

services:
  profile-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Variables de entorno necesarias - ajustar según tu configuración
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

    restart: unless-stopped
    networks:
      - microservices-network
    

networks:
  microservices-network:
    driver: bridge
